on:
  workflow_dispatch: {}
  push:
    paths:
      - '.github/workflows/design.yml'
      - 'parameters/fdWpl-appsWpeWvintegrationWpdnsz-appi-kvWpdnsz.json'
      - 'main.bicep'
      - '!**.md'
      - '!.gitignore'
      - '!assets/**'

env:
  DEPLOYMENT_PARAMETERS: parameters/fdWpl-appsWpeWvintegrationWpdnsz-appi-kvWpdnsz.json
  PROJECT_NAME: design
  DEPLOYMENT_REGION: eastus

name: deploy-architecture-design
jobs:
  test_deploy_on_az:
    environment: ${{ vars.ENVIRONMENT_STAGE }}
    runs-on: ${{ vars.GH_RUNNER_OS }}
    steps:
      - uses: actions/checkout@v3

      - name: login-to-az
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy-architecture-to-az
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ secrets.SUB_ID }}
          deploymentName: ${{env.PROJECT_NAME}}
          region: ${{ env.DEPLOYMENT_REGION }}
          template: ${{ vars.MAIN_BICEP_FILE_PATH }}
          parameters: ${{env.DEPLOYMENT_PARAMETERS}}
          failOnStdErr: true