on:
  push:
    paths:
      - '.github/workflows/imagine.yml'
      - '!**.md'

env:
  DEPLOYMENT_TEMPLATE: https://raw.githubusercontent.com/ArtiomLK/azure-bicephub/df497b2e63ed1073eb98c597f1c93d496dcbba6b/main.bicep
  DEPLOYMENT_PARAMETERS: https://raw.githubusercontent.com/ArtiomLK/azure-reliability-architecture/ceb8f59db06363a4731ce36323698cecdb6f8c28/architectures/fd-premium-app-w-pe/parameters/fd-plan-app.json
  PROJECT_NAME: imagine

name: ${{env.PROJECT_NAME}}
jobs:
  test_deploy_on_az:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: get-files
        run: |
          curl -o template.bicep ${{env.DEPLOYMENT_TEMPLATE}}
          curl -o parameters.bicep ${{env.DEPLOYMENT_PARAMETERS}}

      - name: login-to-az
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy-architecture-to-az
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ secrets.SUB_ID }}
          deploymentName: ${{env.PROJECT_NAME}}
          region: eastus2
          template: template.bicep
          parameters: parameters.bicep
          failOnStdErr: true