on:
  push:
    paths:
      - '.github/workflows/seek.yml'
      - 'parameters/fd-appsWpeWvintegration-pdnsz.json'
      - 'main.bicep'
      - '!**.md'

env:
  DEPLOYMENT_TEMPLATE: main.bicep
  DEPLOYMENT_PARAMETERS: parameters/fd-appsWpeWvintegration-pdnsz.json
  PROJECT_NAME: seek

name: deploy-architecture-seek
jobs:
  test_deploy_on_az:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: login-to-az
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy-architecture-to-az
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ secrets.SUB_ID }}
          deploymentName: ${{env.PROJECT_NAME}}
          region: eastus2
          template: ${{env.DEPLOYMENT_TEMPLATE}}
          parameters: ${{env.DEPLOYMENT_PARAMETERS}}
          failOnStdErr: true