on:
  push:
    paths:
      - '.github/workflows/seek.yml'
      - 'main.bicep'
      - '!**.md'

env:
  DEPLOYMENT_TEMPLATE: main.bicep
  DEPLOYMENT_PARAMETERS: https://raw.githubusercontent.com/ArtiomLK/azure-reliability-architecture/main/architectures/fd-premium-app-w-pe/parameters/fd-plan-appsWpeWvintegration-vnet-pdnsz.json
  PROJECT_NAME: seek

name: deploy-architecture-seek
jobs:
  test_deploy_on_az:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get-files
        run: |
          curl -o parameters.bicep ${{env.DEPLOYMENT_PARAMETERS}}

      - name: login-to-az
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy-architecture-to-az
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ secrets.SUB_ID }}
          deploymentName: ${{env.PROJECT_NAME}}
          region: eastus2
          template: ${{env.DEPLOYMENT_TEMPLATE}}
          parameters: parameters.bicep
          failOnStdErr: true